### PR TITLE
Fix "Goimports local (#58)"

### PR DESCRIPTION
**Pull request by ubergesundheit**
This reverts commit 3af26e3767355727537dcedb8b97315f0366e2df.

### CODE REVIEW

**Comment by TheoBrigitte** [comment]
Why are we removing this now ?

**Comment by ubergesundheit** [comment]
There is something wrong, see https://app.circleci.com/jobs/github/giantswarm/ignition-operator/250 which shouldn’t fail.

I’ll fix this and create another PR with the working implementation

**Comment by ubergesundheit** [comment]
Apologies for not testing this properly, this now works as intended. I've tried it for real in ignition operator now

**Comment by ubergesundheit** [comment]
> Did you also tried in a situation when imports are bad? Do you have the output?

yes:

https://app.circleci.com/jobs/github/giantswarm/ignition-operator/254

**Pull request merged**
