### PR TITLE
Retry creating kind cluster if fails

### PR DESCRIPTION
**Pull request by fiunchinho**
## Checklist

- [X] Make yourself familiar with following readme sections:
    - [X] [Coding Standards](https://github.com/giantswarm/architect-orb#coding-guidelines).
    - [X] [Development](https://github.com/giantswarm/architect-orb#development).
    - [X] [Design and Goals](https://github.com/giantswarm/architect-orb#design-and-goals).
- [X] :warning: Update changelog in [CHANGELOG.md](https://github.com/giantswarm/architect-orb/tree/master/CHANGELOG.md).
- [ ] :warning: After the release update architect orb version in [.circleci/config.yml](https://github.com/giantswarm/architect-orb/tree/master/.circleci/config.yml).

### CODE REVIEW

**Comment by kopiczko** [comment]
This approach should not work. See https://github.com/giantswarm/architect-orb/pull/151#issuecomment-632028465

**Comment by fiunchinho** [comment]
Tried new approach

**Comment by kopiczko** [comment]
So when we are at retries maybe one of you'd like to review https://github.com/giantswarm/architect-orb/pull/151 :D

**Comment by fiunchinho** [comment]
I'm testing the orb on this [PR](https://github.com/giantswarm/azure-operator/pull/823). If it works, I'll merge this.

**Comment by fiunchinho** [comment]
B-E-A-U-T-I-F-U-L

image

**Comment by rossf7** [comment]
> B-E-A-U-T-I-F-U-L

😍

**Comment by fiunchinho** [comment]
We just need a timeout now :sweat: 

image

**Comment by kopiczko** [comment]
> We just need a timeout now 😓

I think you can set that somewhere in the job.

**Comment by kopiczko** [comment]
Or this would hang forever?

**Comment by fiunchinho** [comment]
I meant for the `kind create cluster` command so that if it's taking more than $timeout, we go to the next `attempt`.

**Pull request merged**
