### PR TITLE
helm-chart-template: verify chart version in tagged operator builds

### PR DESCRIPTION
**Pull request by kopiczko**
Towards https://github.com/giantswarm/giantswarm/issues/8635

Tests:
- operator and chart versions don't match https://circleci.com/gh/giantswarm/pawel-test/19
- operator and tag versions don't match https://circleci.com/gh/giantswarm/pawel-test/20
- operator, chart and tag versions match (build fails but the helm-chart-template passes with validation) https://circleci.com/gh/giantswarm/pawel-test/21 

## Checklist

- [x] Update changelog in CHANGELOG.md.
- [ ] After the release update architect orb version in .circleci/config.yml.

### CODE REVIEW

**Comment by kopiczko** [comment]
@oponder I understand your request but I don't want to pollute and possibly break the job to display nicer messages (exit codes are crucial here and `echo` exits with `0`) . I think the diff output is pretty decent (that's why I decided to use diff):

```
diff --git a/.build_operator_version b/.build_chart_version
index 69112e2..e88320d 100644
--- a/.build_operator_version
+++ b/.build_chart_version
@@ -1 +1 @@
-8.1.2-dev
+20.0.0
```

Screenshot 2020-03-09 at 16 29 54

**Comment by JosephSalisbury** [comment]
Yeah, I'm kind of agreeing with @oponder here. I have no idea what that diff means :D

**Comment by kopiczko** [comment]
I think this is fairly simple to "decode":

```
diff --git a/.build_operator_version b/.build_chart_version
index 69112e2..e88320d 100644
--- a/.build_operator_version
+++ b/.build_chart_version
@@ -1 +1 @@
-8.1.2-dev
+20.0.0
```

operator version is 8.1.2-dev and chart version is 20.0.0 and they differ.

I thought about implementation and I think w/o some black magic and using things like `eval` it will be difficult to achieve. I don't know how to carry over the return status and exit with it after `|| echo` with within the same command given that we have `-eo pipefail` bash settings.

Checking return status after running `git diff` doesn't make sense if it fails because the execution will never reach there.

Alternative would be writing an architect binary command which would do the checks but then we lose the explicit nature of the thing and it will be way more time consuming.

I can print debugging cues before executing `git diff` if that's helpful. Otherwise please provide some suggestions to the code because I don't know how to solve this problem. I still think having a check w/o nice messages is more valuable than having broken releases.

**Comment by JosephSalisbury** [comment]
I think some debug cue before the `git diff` would be great.

e.g: "Checking operator version and chart version are the same - this is required in tagged builds" would be grand

**Comment by kopiczko** [comment]
> e.g: "Checking operator version and chart version are the same - this is required in tagged builds" would be grand

Isn't that basically the same thing?
https://github.com/giantswarm/architect-orb/pull/92/files#diff-1a2d1efa4c648bf0b3cfa2fdf8dcaa7dR32

**Comment by JosephSalisbury** [comment]
Oh wow, I really didn't even see that. That feels easy to miss :D

**Comment by kopiczko** [comment]
> Oh wow, I really didn't even see that. That feels easy to miss :D

I don't have impact on the circle UI. I think step names are pretty visible or at least one can get used to that. See https://circleci.com/gh/giantswarm/pawel-test/19.

Can I please get either approval or a suggestion? I feel stuck.

**Comment by JosephSalisbury** [comment]
I think I get the constraints now. @oponder you good?

**Comment by TheoBrigitte** [comment]
Last minute suggestion: how about having this check as a separate job named `ensure operator version and chart version are the same` which only run for tagged build. Then there is no question whether version have to be the same, and it will also avoid all those ifs.

**Comment by kopiczko** [comment]
> Last minute suggestion: how about having this check as a separate job named `ensure operator version and chart version are the same` which only run for tagged build. Then there is no question whether version have to be the same, and it will also avoid all those ifs.

That's a good call. My preference though is to have it in the existing job. That way we don't need to change the existing CI configs. This is very important to have that included in the build because it prevents from having bad releases and packaging the chart is required for having a release. So even if it's a bit uglier I still prefer to have it that way.

**Pull request merged**
