### PR TITLE
Release 8.0.2

### PR DESCRIPTION
**Pull request by rossf7**
:wrench: Please make sure to familiarize yourself with [Development section of README.md](https://github.com/giantswarm/architect-orb/blob/master/README.md#development) before releasing a PR to this repository.

:warning: If you want to **create a new release** of this orb please read [Releases section of README.md](https://github.com/giantswarm/architect-orb/blob/master/README.md#releases) carefully :exclamation:

## Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] After the release update architect orb version in .circleci/config.yml.

### CODE REVIEW

**Comment by yasn77** [comment]
@rossf7 Can we delay this release a little... I creating a PR that will help others with helm lint (see https://github.com/giantswarm/ignition-operator/pull/37). 
Thanks

**Comment by rossf7** [comment]
@yasn77 Yes sure. Just ping me when you're done.

**Comment by yasn77** [comment]
@rossf7 I've opened #99 
Once that is merged, ti would be good to have that shipped in the next release. Thanks

**Comment by rossf7** [comment]
Thanks @oponder! Links are fixed.

**Comment by yasn77** [comment]
@rossf7 #99 was closed and simpler implementation in #100 has been merged. So you are good to go :)

**Comment by rossf7** [comment]
Thanks @yasn77 going with this.

**Pull request merged**
