### PR TITLE
Release v0.10.0

### PR DESCRIPTION
**Pull request by tomahawk28**
## Checklist

- [x] Make yourself familiar with following readme sections:
    - [x] [Coding Standards](https://github.com/giantswarm/architect-orb#coding-guidelines).
    - [x] [Development](https://github.com/giantswarm/architect-orb#development).
    - [x] [Design and Goals](https://github.com/giantswarm/architect-orb#design-and-goals).
- [x] :warning: Update changelog in [CHANGELOG.md](https://github.com/giantswarm/architect-orb/tree/master/CHANGELOG.md).
- [ ] :warning: After the release update architect orb version in [.circleci/config.yml](https://github.com/giantswarm/architect-orb/tree/master/.circleci/config.yml).

### CODE REVIEW

**Comment by corest** [comment]
imo it worth to make it at least `0.10.0` as that's kind of move from completely deprecated version to new one

**Comment by tomahawk28** [comment]
going with a ping

**Comment by tomahawk28** [comment]
@corest I think it makes sense to have v0.10.0, @giantswarm/team-biscuit Do you agree?

**Comment by corest** [comment]
@tomahawk28 I'm biscuit so we agree. But rebase on this https://github.com/giantswarm/architect-orb/pull/164 pls

**Comment by tomahawk28** [comment]
@fiunchinho @corest PTAL

**Pull request merged**
