### PR TITLE
Pin architect binary version to v2.0.0

### PR DESCRIPTION
**Pull request by fiunchinho**
## Checklist

- [x] Make yourself familiar with following readme sections:
    - [x] [Coding Standards](https://github.com/giantswarm/architect-orb#coding-guidelines).
    - [x] [Development](https://github.com/giantswarm/architect-orb#development).
    - [x] [Design and Goals](https://github.com/giantswarm/architect-orb#design-and-goals).
- [x] :warning: Update changelog in [CHANGELOG.md](https://github.com/giantswarm/architect-orb/tree/master/CHANGELOG.md).
- [x] :warning: After the release update architect orb version in [.circleci/config.yml](https://github.com/giantswarm/architect-orb/tree/master/.circleci/config.yml).

### CODE REVIEW

**Comment by tomahawk28** [comment]
Can you test it? I think `architect 1.2.0` has to be included `helm init` commands which is deleted before.

**Comment by fiunchinho** [comment]
> Can you test it? I think `architect 1.2.0` has to be included `helm init` commands which is deleted before.

what's the `architect` version/tag that doesn't need `helm init`?

**Comment by tomahawk28** [comment]
> what's the architect version/tag that doesn't need helm init? 

Only the latest one, https://github.com/giantswarm/architect/commit/b85a96fa76e666da98c0df9f68e874c9a8a09896 I didn't release yet.

**Comment by fiunchinho** [comment]
Changed to use `architect` 2.0.0.

**Pull request merged**
