### PR TITLE
add more parameters to run-kat-tests job

### PR DESCRIPTION
**Pull request by ubergesundheit**
## Checklist

- [x] Make yourself familiar with following readme sections:
    - [x] [Coding Standards](https://github.com/giantswarm/architect-orb#coding-guidelines).
    - [x] [Development](https://github.com/giantswarm/architect-orb#development).
    - [x] [Design and Goals](https://github.com/giantswarm/architect-orb#design-and-goals).
- [x] :warning: Update changelog in [CHANGELOG.md](https://github.com/giantswarm/architect-orb/tree/master/CHANGELOG.md).
- [ ] :warning: After the release update architect orb version in [.circleci/config.yml](https://github.com/giantswarm/architect-orb/tree/master/.circleci/config.yml).

### CODE REVIEW

**Review by piontec — COMMENTED** [review]
I thought we want to make this change transparent to apps using it (except the architect version). But his will force us to add these parameters to all the builds using it, right? I also think that using tag instead of commit hash is a better idea (feel free to tag the current master of `kat`).

**Comment by ubergesundheit** [comment]
I think this will continue working for existing usages, since defaults are defined.

The way the kube-app-testing.sh file is fetched, the parameter accepts both commits, tags and branch names.

**Comment by ubergesundheit** [comment]
Changed default kat version to `v0.5.2`. I don't understand what you mean with

> I thought we want to make this change transparent to apps using it

My impression is that we're introducing sane defaults so after releasing these changes have been released, we only need to update the `architect-orb` version in projects using the `run-kat-tests` job. Please correct me if this is wrong

**Review by piontec — APPROVED** [review]
Sorry, I missed the defaults previously. LGTM :)

**Review by MarcelMue — APPROVED** [review]

**Pull request merged**
