### PR TITLE
Release v0.8.0

### PR DESCRIPTION
**Pull request by tfussell**
## Checklist

- [x] Update changelog in CHANGELOG.md.
- [ ] After the release update architect orb version in .circleci/config.yml.

### CODE REVIEW

**Comment by tfussell** [comment]
There's a weird failure on the `lint` step. `Either git or ssh (required by git to clone through SSH) is not installed in the image.` Found a related issue, but I'm not sure why this is only showing up on a tag https://github.com/CircleCI-Public/shellcheck-orb/issues/9

**Comment by kopiczko** [comment]
> but I'm not sure why this is only showing up on a tag

What do you mean?


In general I feel like this some github<->ci weirdness. You can try to rerun whole workflow. `lint` would pass anyway so if this is one-off quirk I think it's ok to ignore that.

**Comment by tfussell** [comment]
> > but I'm not sure why this is only showing up on a tag
> 
> What do you mean?
> 
> In general I feel like this some github<->ci weirdness. You can try to rerun whole workflow. `lint` would pass anyway so if this is one-off quirk I think it's ok to ignore that.

These are the same code https://circleci.com/gh/giantswarm/architect-orb/1320 https://circleci.com/gh/giantswarm/architect-orb/1325 but the latter one was triggered by my tagging `v0.8.0`. Maybe it's because I should have merged and then tagged rather than tagging the commit on this branch. I will delete the tag to find out.

**Comment by tfussell** [comment]
Looks like it's actually this issue https://discuss.circleci.com/t/checkout-fails-on-workflow-triggered-by-annotated-git-tag/27272 Possible fixes are retagging/editing the image the linter to include a newer version of git or cloning manually.

**Comment by tfussell** [comment]
I pushed a tag temporarily just to ensure that the issue was fixed (didn't actually publish to the orb registry). The job worked that time https://circleci.com/gh/giantswarm/architect-orb/1355 I think this is ready to go now.

**Pull request merged**
