### PR TITLE
Remove unique parameter

### PR DESCRIPTION
**Pull request by kopiczko**
From push-to-app-collection. There are no non-unique apps in the
collection since the release-operator.

### CODE REVIEW

**Review by ubergesundheit — APPROVED** [review]
LGTM. Didn't test this though

**Review by MarcelMue — APPROVED** [review]
Fine with me. I assume you checked that this is covered for all usecases currently?

**Comment by kopiczko** [comment]
> I assume you checked that this is covered for all usecases currently?

What usecases? I know only the usecase of pushing to app collection.

**Comment by kopiczko** [comment]
Seem to work:

- https://github.com/giantswarm/config-controller/pull/40
- https://app.circleci.com/pipelines/github/giantswarm/config-controller/247/workflows/f3f6738f-a23b-4345-8dad-8fdffed4bd5f/jobs/826
- https://github.com/giantswarm/test-app-collection/commit/a303f56bd0d603357ea03bb94245142d7577983b

**Pull request merged**
